= Exercice 2

Nous gérons un ensemble de documents. Un document a un identifiant, un titre, un résumé, un créateur ainsi que la dernière personne
à avoir modifié ce document.
L'identifiant est figé à la création du document et unique. Les titres et les résumés sont éventuellement
modifiables. Le créateur n'est pas modifiable.
Lors d'une modification, la personne modifiant ce document est enregistrée comme dernier modificateur.


. Développez le système présenté ci-dessus. Nous voulons une façade du modèle résumant toutes les
fonctionnalités offertes par le système. Il faut pouvoir, créer un nouvel utilisateur,
enregistrer un nouveau document, modifier le titre d'un document existant,
modifier le résumé d'un document existant, récupérer un document par son identifiant.


. Nous voulons maintenant mettre en place un système de notifications. Chaque utilisateur
possède un ensemble de notifications (les notifications mentionnant les documents dont il est propriétaire
et qui ont été modifié). Mettez en place un système de notifications répondant exactement aux attentes.



